/**
 * LessonsHub Export - HTML Generators
 */

// Generate scheme HTML
function schemeHTML(subject, gradeName, rows) {
  const ref = subject.syllabusRef;
  let tableRows = '';
  
  rows.forEach((r, i) => {
    const bg = r.type === 'exam' ? 'background:#fef2f2' : 
                r.type === 'revision' ? 'background:#fffbeb' : 
                i % 2 === 1 ? 'background:#f8fafc' : '';
    tableRows += `<tr style="${bg}">
      <td style="font-weight:bold;border:1px solid #cbd5e1;padding:3px">${r.week}</td>
      <td style="border:1px solid #cbd5e1;padding:3px">${r.topic}</td>
      <td style="border:1px solid #cbd5e1;padding:3px">${r.competence}</td>
      <td style="border:1px solid #cbd5e1;padding:3px">${r.keyConcept}</td>
      <td style="border:1px solid #cbd5e1;padding:3px">${r.activity}</td>
      <td style="border:1px solid #cbd5e1;padding:3px">${r.assessment}</td>
      <td style="border:1px solid #cbd5e1;padding:3px">${r.materials}</td>
      <td style="border:1px solid #cbd5e1;padding:3px">${r.expectedStandard}</td>
      <td style="border:1px solid #cbd5e1;padding:3px">${r.reference}</td>
    </tr>`;
  });
  
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Scheme of Work - ${subject.name} ${gradeName}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; color: #1e293b; }
    .header { text-align: center; border-bottom: 2px solid #1e40af; padding: 15px; margin-bottom: 20px; }
    .header h1 { font-size: 20px; font-weight: bold; margin: 5px 0; }
    .header h2 { font-size: 14px; color: #1e40af; margin: 5px 0; }
    .header p { font-size: 12px; margin: 5px 0; }
    table { width: 100%; border-collapse: collapse; font-size: 11px; }
    th { background: #1e40af; color: white; padding: 6px; text-align: left; }
    td { padding: 4px; border: 1px solid #cbd5e1; word-wrap: break-word; }
    .footer { margin-top: 20px; font-size: 10px; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 10px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>LINDA SECONDARY SCHOOL</h1>
    <h2>SCHEMES OF WORK</h2>
    <p>SUBJECT: ${subject.name.toUpperCase()} | LEVEL: ${gradeName.toUpperCase()} | TERM: 3 | YEAR: 2026</p>
  </div>
  <table>
    <thead>
      <tr>
        <th>WK</th><th>TOPIC</th><th>SPECIFIC COMPETENCES</th>
        <th>KEY CONCEPTS</th><th>LEARNING ACTIVITY</th><th>ASSESSMENT</th>
        <th>TEACHING MATERIALS</th><th>EXPECTED STANDARD</th><th>REFERENCE</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <div class="footer">
    Reference: ${ref} | Generated by LessonsHub | ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`;
}

module.exports = { schemeHTML };
